#!/bin/bash
sudo apt install hashcat
sudo apt install hcxtools
sudo apt install hcxdumptool
clear
# Set the directory to the current directory
directory=$(pwd)

# Create an array to store the file names
files=()

# Iterate over each .pcap or .cap file in the directory and add it to the array
count=1
for file in "$directory"/*.pcap "$directory"/*.cap; do
    [[ -f "$file" ]] && files+=("$(basename "$file")")
    count=$((count + 1))
done

# Display the list of files
echo "Select a file:"
for ((i=0; i<${#files[@]}; i++)); do
    echo "$((i+1)). ${files[$i]}"
done

# Prompt the user for their selection
read -p "Enter the number of the file you want to select: " selection_number

# Validate the user's input
if [[ $selection_number =~ ^[0-9]+$ ]]; then
    if (( selection_number >= 1 && selection_number <= ${#files[@]} )); then
        selected_file=${files[$((selection_number-1))]}
        echo "Selected file: $selected_file"
    else
        echo "Invalid selection. Please enter a valid number."
        exit
    fi
else
    echo "Invalid input. Please enter a valid number."
    exit
fi
pcapfile=${selected_file%.*}
#crack command
clear

hcxpcapngtool -o ${pcapfile}.hc22000 -E essidlist $selected_file
hashcat -m 22000 ${pcapfile}.hc22000 -a 3 --increment --increment-min 4 --increment-max 15 ?d?d?d?d?d?d?d?d?d?d?d?d?d?d?d
rm ${pcapfile}.hc22000
