#!/bin/bash
sudo apt update
sudo apt install flatpak -y
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub vinegar -y
flatpak update -y
