#!/bin/bash
cd
mkdir chatgptinstall
sleep 2
cd chatgptinstall
wget -c https://github.com/lencx/ChatGPT/releases/download/v0.12.0/ChatGPT_0.12.0_linux_x86_64.deb
sudo apt install ./*.deb
cd
sudo rm -rf chatgptinstall
