#!/bin/bash
cd
mkdir mods
cd mods
mkdir 1.19.3
mkdir 1.19.2
mkdir 1.18.2
mkdir 1.17.1
mkdir 1.16.5
mkdir 1.19.3forge
mkdir 1.19.2forge
mkdir 1.18.2forge
mkdir 1.17.1forge
mkdir 1.16.5forge
echo "now look in your home folder for the folder called mods!"
