#!/bin/bash
sudo apt update && sudo apt upgrade -y
sudo apt install git neofetch -y
cd
git clone https://github.com/MrScratchcat/custom-linux-commands
cd custom-linux-commands/
sudo cp * /bin
cd /bin
sudo chmod +x *
cd
sudo rm -r custom-linux-commands/

# Check if neofetch is already present in .bashrc
if ! grep -q "neofetch" ~/.bashrc; then
    echo 'neofetch' >> ~/.bashrc
    echo "Added 'neofetch' command to .bashrc"
else
    echo "The 'neofetch' command is already present in .bashrc"
fi

gpu=$(lspci | grep -i vga | awk '{print $5}')
kernel=$(uname -r)

if [ $gpu == "NVIDIA" ]
then
    sudo apt install nvidia-driver-535 -y
    if [ $kernel == 5.15.0-76-generic ]
    then
        sudo apt update
        sudo apt install linux-oem-22.04d
        clear
    fi
fi 
if [ $kernel == 5.19.0-38-generic ]
then
    echo "your up to date please reboot now"
else
    echo "your up to date!"
fi
