#!/bin/bash
cd
sudo apt update 
sudo apt upgrade -y
sudo apt install bully hashcat hcxdumptool hcxtools macchanger wifite gnome-software-plugin-flatpak flatpak neofetch net-tools wireshark curl gimp filezilla wine dialog wireless-tools dialog neofetch git wget curl openjdk-19-jdk ettercap-graphical python3-pip gpsd gpsd-clients python3-tk python3-setuptools python3-pyqt5.qtchart bettercap docker.io -y
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub -y
flatpak install flathub io.missioncenter.MissionCenter -y
flatpak install flathub com.visualstudio.code -y
flatpak install discord vinegar -y
flatpak update
sudo pip3 install QScintilla gps3 dronekit manuf python-dateutil numpy matplotlib
mkdir hacking-tools
cd hacking-tools 
git clone https://github.com/tegal1337/CiLocks
git clone https://github.com/KasRoudra/PyPhisher
git clone https://github.com/htr-tech/zphisher
git clone https://github.com/KasRoudra/MaxPhisher
git clone https://github.com/TheSpeedX/TBomb
git clone https://github.com/AngelSecurityTeam/Cam-Hackers
git clone https://github.com/thewhiteh4t/seeker
git clone https://github.com/sherlock-project/sherlock
git clone https://github.com/beefproject/beef/
cd
git clone https://github.com/MrScratchcat/auto-minecraft-server
wget -O minecraft.deb https://launcher.mojang.com/download/Minecraft.deb
sudo apt install -y ./minecraft.deb
sudo chown -R $USER: $HOME
if ! grep -q "neofetch" ~/.bashrc; then
    echo 'neofetch' >> ~/.bashrc
    echo "Added 'neofetch' command to .bashrc"
else
    echo "The 'neofetch' command is already present in .bashrc"
fi
echo "all done"

